### PR TITLE
Note about code signature verification

### PR DESCRIPTION
**Pull request by aysiu**
pkgutil --check-signature /Users/USERNAME/Downloads/dockutil-2.0.3.pkg 
Package "dockutil-2.0.3.pkg":
   Status: no signature

That's using the .pkg from https://github.com/kcrawford/dockutil/releases

### CODE REVIEW

**Comment by jessepeterson** [comment]
We actually don't even use the releases page: we pull direct from the raw github source. There's probably some argument to be to use the releases, though. Especially if they were to be signed. Pinging @kcrawford.

**Comment by kcrawford** [comment]
I recently started uploading the releases. But I don't have my own apple developer membership to sign the pkg ☹️.

**Comment by aysiu** [comment]
@kcrawford I got you. It's really just a note to let people know that the code signature verification is missing from the recipe, because there's nothing to verify.

More details here:
https://groups.google.com/d/msg/autopkg-discuss/16PuKLT3YvU/VF9jYNntBwAJ

**Comment by jessepeterson** [comment]
I'll close this for now until some solution for signing is available.

**Pull request closed without merging**
