### PR TITLE
Split the CUDADriver recipe into a download and a munki part.

### PR DESCRIPTION
**Pull request by mkuron**
Split the CUDADriver recipe into a download and a Munki part. That way, I can use it with the [Importer](https://github.com/mkuron/autopkg-recipes/blob/master/MunkiServerImporter.py) I wrote for [MunkiServer](https://github.com/jnraine/munkiserver).

### CODE REVIEW

**Comment by jessepeterson** [comment]
Yikes, sorry for not seeing updates on this! What's the current status? The CUDADriver package appears to be downloading fine now — perhaps they relaxed the requirement?

**Comment by mkuron** [comment]
This probably depends on the system Python version. Most web servers now disable SSLv3 for security reasons, and probably only newer Python versions (OS X 10.10 and higher maybe?) default to TLS. So I'd suggest keeping the `curl` for better compatibility and in case Nvidia ever decides to make another change to their HTTPS configuration.

**Comment by timsutton** [comment]
For me the recipe currently works without `curl`. A couple comments to follow in @mkuron's most recent commit..

**Comment by mkuron** [comment]
Here's the commit that merges the latest changes from master. I think the pull request is ready to merge now.

**Pull request merged**
