### PR TITLE
Download latest release instead of binary

### PR DESCRIPTION
**Pull request by aysiu**
This will get only the latest release instead of the modified binary in the GitHub project.

### CODE REVIEW

**Comment by jessepeterson** [comment]
I support this change — at the time of creation I don't think it was being "released" via Github.

However, I think it needs a bit more work. Oddly, the Munki recipe does not use the download recipe. As well I think it ought to use the GitHubReleases processor instead.

**Comment by aysiu** [comment]
Yeah, the download recipe Graham Gilbert has for Outset uses the GitHubReleasesInfoProvider processor:
https://github.com/autopkg/grahamgilbert-recipes/blob/master/outset/outset.download.recipe

**Comment by aysiu** [comment]
Okay. I've made the change using the GitHubReleasesInfoProvider.

**Comment by jessepeterson** [comment]
Thanks @aysiu! I also updated the `.pkg` and `.munki` recipes to use the download recipe.

**Pull request merged**
